Katacoda.com is now closed
learnk8s/free-kubernetes pull request #26
Opened 2022-10-12 23:44 UTC by redwerkz

2022-10-13 01:28 UTC, kaovilai requested changes

2022-10-13 01:28 UTC, kaovilai commented on README.md
> +  - Link: [https://www.oreilly.com/online-learning/leveraging-katacoda-technology.html](https://www.oreilly.com/online-learning/leveraging-katacoda-technology.html)
```suggestion
- **Killercoda**
  - Description: Interactive environments, Access interactive environments simply in the browser. Study scenarios by others or create scenarios for your students. Run Katacoda scenarios on Killercoda.
  - Link: [https://killercoda.com/](https://killercoda.com/)
- ~~Katacoda~~
  - Description: Katacoda.com is now closed. Learn more about this decision and access interactive learning on O’Reilly.
  - Link: [https://www.oreilly.com/online-learning/leveraging-katacoda-technology.html](https://www.oreilly.com/online-learning/leveraging-katacoda-technology.html)
```

2022-10-16 19:54 UTC, salaboy commented
Can you please rebase this PR and remove Katacoda.. there is no need to keep it if it is not longer operational.

2022-10-17 03:25 UTC, kaovilai commented
Duplicate #24

2022-10-17 10:59 UTC, closed without merging